// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        (unknown)
// source: coop/drivers/geo/v1beta1/distance.proto

package v1beta1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetDistanceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Place_1Id string `protobuf:"bytes,1,opt,name=place_1_id,json=place1Id,proto3" json:"place_1_id,omitempty"`
	Place_2Id string `protobuf:"bytes,2,opt,name=place_2_id,json=place2Id,proto3" json:"place_2_id,omitempty"`
}

func (x *GetDistanceRequest) Reset() {
	*x = GetDistanceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_coop_drivers_geo_v1beta1_distance_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDistanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDistanceRequest) ProtoMessage() {}

func (x *GetDistanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coop_drivers_geo_v1beta1_distance_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDistanceRequest.ProtoReflect.Descriptor instead.
func (*GetDistanceRequest) Descriptor() ([]byte, []int) {
	return file_coop_drivers_geo_v1beta1_distance_proto_rawDescGZIP(), []int{0}
}

func (x *GetDistanceRequest) GetPlace_1Id() string {
	if x != nil {
		return x.Place_1Id
	}
	return ""
}

func (x *GetDistanceRequest) GetPlace_2Id() string {
	if x != nil {
		return x.Place_2Id
	}
	return ""
}

type GetDistanceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Duration       *durationpb.Duration `protobuf:"bytes,1,opt,name=duration,proto3" json:"duration,omitempty"`
	DistanceMeters int32                `protobuf:"varint,2,opt,name=distance_meters,json=distanceMeters,proto3" json:"distance_meters,omitempty"`
}

func (x *GetDistanceResponse) Reset() {
	*x = GetDistanceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_coop_drivers_geo_v1beta1_distance_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDistanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDistanceResponse) ProtoMessage() {}

func (x *GetDistanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_coop_drivers_geo_v1beta1_distance_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDistanceResponse.ProtoReflect.Descriptor instead.
func (*GetDistanceResponse) Descriptor() ([]byte, []int) {
	return file_coop_drivers_geo_v1beta1_distance_proto_rawDescGZIP(), []int{1}
}

func (x *GetDistanceResponse) GetDuration() *durationpb.Duration {
	if x != nil {
		return x.Duration
	}
	return nil
}

func (x *GetDistanceResponse) GetDistanceMeters() int32 {
	if x != nil {
		return x.DistanceMeters
	}
	return 0
}

var File_coop_drivers_geo_v1beta1_distance_proto protoreflect.FileDescriptor

var file_coop_drivers_geo_v1beta1_distance_proto_rawDesc = []byte{
	0x0a, 0x27, 0x63, 0x6f, 0x6f, 0x70, 0x2f, 0x64, 0x72, 0x69, 0x76, 0x65, 0x72, 0x73, 0x2f, 0x67,
	0x65, 0x6f, 0x2f, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x2f, 0x64, 0x69, 0x73, 0x74, 0x61,
	0x6e, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x18, 0x63, 0x6f, 0x6f, 0x70, 0x2e,
	0x64, 0x72, 0x69, 0x76, 0x65, 0x72, 0x73, 0x2e, 0x67, 0x65, 0x6f, 0x2e, 0x76, 0x31, 0x62, 0x65,
	0x74, 0x61, 0x31, 0x1a, 0x1e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x50, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x44, 0x69, 0x73, 0x74, 0x61, 0x6e,
	0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x0a, 0x70, 0x6c, 0x61,
	0x63, 0x65, 0x5f, 0x31, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70,
	0x6c, 0x61, 0x63, 0x65, 0x31, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x0a, 0x70, 0x6c, 0x61, 0x63, 0x65,
	0x5f, 0x32, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x6c, 0x61,
	0x63, 0x65, 0x32, 0x49, 0x64, 0x22, 0x75, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x44, 0x69, 0x73, 0x74,
	0x61, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x35, 0x0a, 0x08,
	0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x27, 0x0a, 0x0f, 0x64, 0x69, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x5f,
	0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e, 0x64, 0x69,
	0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x4d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x42, 0x4b, 0x5a, 0x49,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6b, 0x65, 0x76, 0x69, 0x6e,
	0x6d, 0x69, 0x63, 0x68, 0x61, 0x65, 0x6c, 0x63, 0x68, 0x65, 0x6e, 0x2f, 0x61, 0x70, 0x69, 0x2d,
	0x67, 0x65, 0x6f, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x69, 0x64, 0x6c,
	0x2f, 0x63, 0x6f, 0x6f, 0x70, 0x2f, 0x64, 0x72, 0x69, 0x76, 0x65, 0x72, 0x73, 0x2f, 0x67, 0x65,
	0x6f, 0x2f, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_coop_drivers_geo_v1beta1_distance_proto_rawDescOnce sync.Once
	file_coop_drivers_geo_v1beta1_distance_proto_rawDescData = file_coop_drivers_geo_v1beta1_distance_proto_rawDesc
)

func file_coop_drivers_geo_v1beta1_distance_proto_rawDescGZIP() []byte {
	file_coop_drivers_geo_v1beta1_distance_proto_rawDescOnce.Do(func() {
		file_coop_drivers_geo_v1beta1_distance_proto_rawDescData = protoimpl.X.CompressGZIP(file_coop_drivers_geo_v1beta1_distance_proto_rawDescData)
	})
	return file_coop_drivers_geo_v1beta1_distance_proto_rawDescData
}

var file_coop_drivers_geo_v1beta1_distance_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_coop_drivers_geo_v1beta1_distance_proto_goTypes = []interface{}{
	(*GetDistanceRequest)(nil),  // 0: coop.drivers.geo.v1beta1.GetDistanceRequest
	(*GetDistanceResponse)(nil), // 1: coop.drivers.geo.v1beta1.GetDistanceResponse
	(*durationpb.Duration)(nil), // 2: google.protobuf.Duration
}
var file_coop_drivers_geo_v1beta1_distance_proto_depIdxs = []int32{
	2, // 0: coop.drivers.geo.v1beta1.GetDistanceResponse.duration:type_name -> google.protobuf.Duration
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_coop_drivers_geo_v1beta1_distance_proto_init() }
func file_coop_drivers_geo_v1beta1_distance_proto_init() {
	if File_coop_drivers_geo_v1beta1_distance_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_coop_drivers_geo_v1beta1_distance_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDistanceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_coop_drivers_geo_v1beta1_distance_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDistanceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_coop_drivers_geo_v1beta1_distance_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_coop_drivers_geo_v1beta1_distance_proto_goTypes,
		DependencyIndexes: file_coop_drivers_geo_v1beta1_distance_proto_depIdxs,
		MessageInfos:      file_coop_drivers_geo_v1beta1_distance_proto_msgTypes,
	}.Build()
	File_coop_drivers_geo_v1beta1_distance_proto = out.File
	file_coop_drivers_geo_v1beta1_distance_proto_rawDesc = nil
	file_coop_drivers_geo_v1beta1_distance_proto_goTypes = nil
	file_coop_drivers_geo_v1beta1_distance_proto_depIdxs = nil
}
