// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        (unknown)
// source: coop/drivers/geo/v1beta1/geocode.proto

package v1beta1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LocationType int32

const (
	LocationType_LOCATION_TYPE_INVALID LocationType = 0
	// Indicates that the returned result is a precise geocode for which we have
	// location information accurate down to street address precision.
	LocationType_LOCATION_TYPE_ROOFTOP LocationType = 1
	// Indicates that the returned result reflects an approximation (usually on a
	// road) interpolated between two precise points (such as intersections).
	// Interpolated results are generally returned when rooftop geocodes are
	// unavailable for a street address.
	LocationType_LOCATION_TYPE_RANGE_INTERPOLATED LocationType = 2
	// Indicates that the returned result is the geometric center of a result such
	// as a polyline (for example, a street) or polygon (region).
	LocationType_LOCATION_TYPE_GEOMETRIC_CENTER LocationType = 3
	// Indicates that the returned result is approximate.
	LocationType_LOCATION_TYPE_APPROXIMATE LocationType = 4
)

// Enum value maps for LocationType.
var (
	LocationType_name = map[int32]string{
		0: "LOCATION_TYPE_INVALID",
		1: "LOCATION_TYPE_ROOFTOP",
		2: "LOCATION_TYPE_RANGE_INTERPOLATED",
		3: "LOCATION_TYPE_GEOMETRIC_CENTER",
		4: "LOCATION_TYPE_APPROXIMATE",
	}
	LocationType_value = map[string]int32{
		"LOCATION_TYPE_INVALID":            0,
		"LOCATION_TYPE_ROOFTOP":            1,
		"LOCATION_TYPE_RANGE_INTERPOLATED": 2,
		"LOCATION_TYPE_GEOMETRIC_CENTER":   3,
		"LOCATION_TYPE_APPROXIMATE":        4,
	}
)

func (x LocationType) Enum() *LocationType {
	p := new(LocationType)
	*p = x
	return p
}

func (x LocationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LocationType) Descriptor() protoreflect.EnumDescriptor {
	return file_coop_drivers_geo_v1beta1_geocode_proto_enumTypes[0].Descriptor()
}

func (LocationType) Type() protoreflect.EnumType {
	return &file_coop_drivers_geo_v1beta1_geocode_proto_enumTypes[0]
}

func (x LocationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LocationType.Descriptor instead.
func (LocationType) EnumDescriptor() ([]byte, []int) {
	return file_coop_drivers_geo_v1beta1_geocode_proto_rawDescGZIP(), []int{0}
}

type GeocodeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlaceId string `protobuf:"bytes,1,opt,name=place_id,json=placeId,proto3" json:"place_id,omitempty"`
}

func (x *GeocodeRequest) Reset() {
	*x = GeocodeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_coop_drivers_geo_v1beta1_geocode_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GeocodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeocodeRequest) ProtoMessage() {}

func (x *GeocodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coop_drivers_geo_v1beta1_geocode_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeocodeRequest.ProtoReflect.Descriptor instead.
func (*GeocodeRequest) Descriptor() ([]byte, []int) {
	return file_coop_drivers_geo_v1beta1_geocode_proto_rawDescGZIP(), []int{0}
}

func (x *GeocodeRequest) GetPlaceId() string {
	if x != nil {
		return x.PlaceId
	}
	return ""
}

type GeocodeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LatLng *LatLng `protobuf:"bytes,1,opt,name=lat_lng,json=latLng,proto3" json:"lat_lng,omitempty"`
}

func (x *GeocodeResponse) Reset() {
	*x = GeocodeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_coop_drivers_geo_v1beta1_geocode_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GeocodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeocodeResponse) ProtoMessage() {}

func (x *GeocodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_coop_drivers_geo_v1beta1_geocode_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeocodeResponse.ProtoReflect.Descriptor instead.
func (*GeocodeResponse) Descriptor() ([]byte, []int) {
	return file_coop_drivers_geo_v1beta1_geocode_proto_rawDescGZIP(), []int{1}
}

func (x *GeocodeResponse) GetLatLng() *LatLng {
	if x != nil {
		return x.LatLng
	}
	return nil
}

type ReverseGeocodeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LatLng *LatLng `protobuf:"bytes,1,opt,name=lat_lng,json=latLng,proto3" json:"lat_lng,omitempty"`
}

func (x *ReverseGeocodeRequest) Reset() {
	*x = ReverseGeocodeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_coop_drivers_geo_v1beta1_geocode_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReverseGeocodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReverseGeocodeRequest) ProtoMessage() {}

func (x *ReverseGeocodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coop_drivers_geo_v1beta1_geocode_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReverseGeocodeRequest.ProtoReflect.Descriptor instead.
func (*ReverseGeocodeRequest) Descriptor() ([]byte, []int) {
	return file_coop_drivers_geo_v1beta1_geocode_proto_rawDescGZIP(), []int{2}
}

func (x *ReverseGeocodeRequest) GetLatLng() *LatLng {
	if x != nil {
		return x.LatLng
	}
	return nil
}

type ReverseGeocodeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Results []*GeocodingResult `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
}

func (x *ReverseGeocodeResponse) Reset() {
	*x = ReverseGeocodeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_coop_drivers_geo_v1beta1_geocode_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReverseGeocodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReverseGeocodeResponse) ProtoMessage() {}

func (x *ReverseGeocodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_coop_drivers_geo_v1beta1_geocode_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReverseGeocodeResponse.ProtoReflect.Descriptor instead.
func (*ReverseGeocodeResponse) Descriptor() ([]byte, []int) {
	return file_coop_drivers_geo_v1beta1_geocode_proto_rawDescGZIP(), []int{3}
}

func (x *ReverseGeocodeResponse) GetResults() []*GeocodingResult {
	if x != nil {
		return x.Results
	}
	return nil
}

// GeocodingResult is a single geocoded address
type GeocodingResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// An array containing the separate components applicable to this address.
	AddressComponents []*AddressComponent `protobuf:"bytes,1,rep,name=address_components,json=addressComponents,proto3" json:"address_components,omitempty"`
	// A string containing the human-readable address of this location.
	FormattedAddress string           `protobuf:"bytes,2,opt,name=formatted_address,json=formattedAddress,proto3" json:"formatted_address,omitempty"`
	AddressGeometry  *AddressGeometry `protobuf:"bytes,3,opt,name=address_geometry,json=addressGeometry,proto3" json:"address_geometry,omitempty"`
	// Contains a set of zero or more tags identifying the type of feature
	// returned in the result. For example, a geocode of "Chicago" returns
	// "locality" which indicates that "Chicago" is a city, and also returns
	// "political" which indicates it is a political entity.
	Types []string `protobuf:"bytes,4,rep,name=types,proto3" json:"types,omitempty"`
	// A unique identifier that can be used with other Google APIs.
	PlaceId string `protobuf:"bytes,5,opt,name=place_id,json=placeId,proto3" json:"place_id,omitempty"`
}

func (x *GeocodingResult) Reset() {
	*x = GeocodingResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_coop_drivers_geo_v1beta1_geocode_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GeocodingResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeocodingResult) ProtoMessage() {}

func (x *GeocodingResult) ProtoReflect() protoreflect.Message {
	mi := &file_coop_drivers_geo_v1beta1_geocode_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeocodingResult.ProtoReflect.Descriptor instead.
func (*GeocodingResult) Descriptor() ([]byte, []int) {
	return file_coop_drivers_geo_v1beta1_geocode_proto_rawDescGZIP(), []int{4}
}

func (x *GeocodingResult) GetAddressComponents() []*AddressComponent {
	if x != nil {
		return x.AddressComponents
	}
	return nil
}

func (x *GeocodingResult) GetFormattedAddress() string {
	if x != nil {
		return x.FormattedAddress
	}
	return ""
}

func (x *GeocodingResult) GetAddressGeometry() *AddressGeometry {
	if x != nil {
		return x.AddressGeometry
	}
	return nil
}

func (x *GeocodingResult) GetTypes() []string {
	if x != nil {
		return x.Types
	}
	return nil
}

func (x *GeocodingResult) GetPlaceId() string {
	if x != nil {
		return x.PlaceId
	}
	return ""
}

// LatLngBounds represents a bounded square area on the Earth.
type LatLngBounds struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Northeast *LatLng `protobuf:"bytes,1,opt,name=northeast,proto3" json:"northeast,omitempty"`
	Southwest *LatLng `protobuf:"bytes,2,opt,name=southwest,proto3" json:"southwest,omitempty"`
}

func (x *LatLngBounds) Reset() {
	*x = LatLngBounds{}
	if protoimpl.UnsafeEnabled {
		mi := &file_coop_drivers_geo_v1beta1_geocode_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LatLngBounds) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LatLngBounds) ProtoMessage() {}

func (x *LatLngBounds) ProtoReflect() protoreflect.Message {
	mi := &file_coop_drivers_geo_v1beta1_geocode_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LatLngBounds.ProtoReflect.Descriptor instead.
func (*LatLngBounds) Descriptor() ([]byte, []int) {
	return file_coop_drivers_geo_v1beta1_geocode_proto_rawDescGZIP(), []int{5}
}

func (x *LatLngBounds) GetNortheast() *LatLng {
	if x != nil {
		return x.Northeast
	}
	return nil
}

func (x *LatLngBounds) GetSouthwest() *LatLng {
	if x != nil {
		return x.Southwest
	}
	return nil
}

// AddressGeometry is the location of a an address
type AddressGeometry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Contains the geocoded latitude, longitude value. For normal address
	// lookups, this field is typically the most important.
	Location *LatLng `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	// Stores additional data about the specified location.
	LocationType LocationType `protobuf:"varint,2,opt,name=location_type,json=locationType,proto3,enum=coop.drivers.geo.v1beta1.LocationType" json:"location_type,omitempty"`
	// Stores the bounding box which can fully contain the returned result. Note
	// that these bounds may not match the recommended viewport. (For example, San
	// Francisco includes the Farallon islands, which are technically part of the
	// city, but probably should not be returned in the viewport.)
	// (Optionally returned).
	Bounds *LatLngBounds `protobuf:"bytes,3,opt,name=bounds,proto3" json:"bounds,omitempty"`
	// Contains the recommended viewport for displaying the returned result,
	// specified as two latitude,longitude values defining the southwest and
	// northeast corner of the viewport bounding box. Generally the viewport is
	// used to frame a result when displaying it to a user.
	Viewport *LatLngBounds `protobuf:"bytes,4,opt,name=viewport,proto3" json:"viewport,omitempty"`
	Types    []string      `protobuf:"bytes,5,rep,name=types,proto3" json:"types,omitempty"`
}

func (x *AddressGeometry) Reset() {
	*x = AddressGeometry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_coop_drivers_geo_v1beta1_geocode_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddressGeometry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddressGeometry) ProtoMessage() {}

func (x *AddressGeometry) ProtoReflect() protoreflect.Message {
	mi := &file_coop_drivers_geo_v1beta1_geocode_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddressGeometry.ProtoReflect.Descriptor instead.
func (*AddressGeometry) Descriptor() ([]byte, []int) {
	return file_coop_drivers_geo_v1beta1_geocode_proto_rawDescGZIP(), []int{6}
}

func (x *AddressGeometry) GetLocation() *LatLng {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *AddressGeometry) GetLocationType() LocationType {
	if x != nil {
		return x.LocationType
	}
	return LocationType_LOCATION_TYPE_INVALID
}

func (x *AddressGeometry) GetBounds() *LatLngBounds {
	if x != nil {
		return x.Bounds
	}
	return nil
}

func (x *AddressGeometry) GetViewport() *LatLngBounds {
	if x != nil {
		return x.Viewport
	}
	return nil
}

func (x *AddressGeometry) GetTypes() []string {
	if x != nil {
		return x.Types
	}
	return nil
}

// AddressComponent is a part of an address
type AddressComponent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LongName  string `protobuf:"bytes,1,opt,name=long_name,json=longName,proto3" json:"long_name,omitempty"`
	ShortName string `protobuf:"bytes,2,opt,name=short_name,json=shortName,proto3" json:"short_name,omitempty"`
	// See supported types:
	// https://developers.google.com/maps/documentation/places/web-service/supported_types
	Types []string `protobuf:"bytes,3,rep,name=types,proto3" json:"types,omitempty"`
}

func (x *AddressComponent) Reset() {
	*x = AddressComponent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_coop_drivers_geo_v1beta1_geocode_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddressComponent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddressComponent) ProtoMessage() {}

func (x *AddressComponent) ProtoReflect() protoreflect.Message {
	mi := &file_coop_drivers_geo_v1beta1_geocode_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddressComponent.ProtoReflect.Descriptor instead.
func (*AddressComponent) Descriptor() ([]byte, []int) {
	return file_coop_drivers_geo_v1beta1_geocode_proto_rawDescGZIP(), []int{7}
}

func (x *AddressComponent) GetLongName() string {
	if x != nil {
		return x.LongName
	}
	return ""
}

func (x *AddressComponent) GetShortName() string {
	if x != nil {
		return x.ShortName
	}
	return ""
}

func (x *AddressComponent) GetTypes() []string {
	if x != nil {
		return x.Types
	}
	return nil
}

var File_coop_drivers_geo_v1beta1_geocode_proto protoreflect.FileDescriptor

var file_coop_drivers_geo_v1beta1_geocode_proto_rawDesc = []byte{
	0x0a, 0x26, 0x63, 0x6f, 0x6f, 0x70, 0x2f, 0x64, 0x72, 0x69, 0x76, 0x65, 0x72, 0x73, 0x2f, 0x67,
	0x65, 0x6f, 0x2f, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x2f, 0x67, 0x65, 0x6f, 0x63, 0x6f,
	0x64, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x18, 0x63, 0x6f, 0x6f, 0x70, 0x2e, 0x64,
	0x72, 0x69, 0x76, 0x65, 0x72, 0x73, 0x2e, 0x67, 0x65, 0x6f, 0x2e, 0x76, 0x31, 0x62, 0x65, 0x74,
	0x61, 0x31, 0x1a, 0x25, 0x63, 0x6f, 0x6f, 0x70, 0x2f, 0x64, 0x72, 0x69, 0x76, 0x65, 0x72, 0x73,
	0x2f, 0x67, 0x65, 0x6f, 0x2f, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x2f, 0x6c, 0x61, 0x74,
	0x6c, 0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2b, 0x0a, 0x0e, 0x47, 0x65, 0x6f,
	0x63, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x70,
	0x6c, 0x61, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70,
	0x6c, 0x61, 0x63, 0x65, 0x49, 0x64, 0x22, 0x4c, 0x0a, 0x0f, 0x47, 0x65, 0x6f, 0x63, 0x6f, 0x64,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x39, 0x0a, 0x07, 0x6c, 0x61, 0x74,
	0x5f, 0x6c, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x63, 0x6f, 0x6f,
	0x70, 0x2e, 0x64, 0x72, 0x69, 0x76, 0x65, 0x72, 0x73, 0x2e, 0x67, 0x65, 0x6f, 0x2e, 0x76, 0x31,
	0x62, 0x65, 0x74, 0x61, 0x31, 0x2e, 0x4c, 0x61, 0x74, 0x4c, 0x6e, 0x67, 0x52, 0x06, 0x6c, 0x61,
	0x74, 0x4c, 0x6e, 0x67, 0x22, 0x52, 0x0a, 0x15, 0x52, 0x65, 0x76, 0x65, 0x72, 0x73, 0x65, 0x47,
	0x65, 0x6f, 0x63, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x39, 0x0a,
	0x07, 0x6c, 0x61, 0x74, 0x5f, 0x6c, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20,
	0x2e, 0x63, 0x6f, 0x6f, 0x70, 0x2e, 0x64, 0x72, 0x69, 0x76, 0x65, 0x72, 0x73, 0x2e, 0x67, 0x65,
	0x6f, 0x2e, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x2e, 0x4c, 0x61, 0x74, 0x4c, 0x6e, 0x67,
	0x52, 0x06, 0x6c, 0x61, 0x74, 0x4c, 0x6e, 0x67, 0x22, 0x5d, 0x0a, 0x16, 0x52, 0x65, 0x76, 0x65,
	0x72, 0x73, 0x65, 0x47, 0x65, 0x6f, 0x63, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x43, 0x0a, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x63, 0x6f, 0x6f, 0x70, 0x2e, 0x64, 0x72, 0x69, 0x76, 0x65,
	0x72, 0x73, 0x2e, 0x67, 0x65, 0x6f, 0x2e, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x2e, 0x47,
	0x65, 0x6f, 0x63, 0x6f, 0x64, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x07,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x22, 0xa0, 0x02, 0x0a, 0x0f, 0x47, 0x65, 0x6f, 0x63,
	0x6f, 0x64, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x59, 0x0a, 0x12, 0x61,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x5f, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x63, 0x6f, 0x6f, 0x70, 0x2e, 0x64,
	0x72, 0x69, 0x76, 0x65, 0x72, 0x73, 0x2e, 0x67, 0x65, 0x6f, 0x2e, 0x76, 0x31, 0x62, 0x65, 0x74,
	0x61, 0x31, 0x2e, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x6e,
	0x65, 0x6e, 0x74, 0x52, 0x11, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x43, 0x6f, 0x6d, 0x70,
	0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x2b, 0x0a, 0x11, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74,
	0x74, 0x65, 0x64, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x10, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x74, 0x65, 0x64, 0x41, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x12, 0x54, 0x0a, 0x10, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x5f, 0x67,
	0x65, 0x6f, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x29, 0x2e,
	0x63, 0x6f, 0x6f, 0x70, 0x2e, 0x64, 0x72, 0x69, 0x76, 0x65, 0x72, 0x73, 0x2e, 0x67, 0x65, 0x6f,
	0x2e, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x2e, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x47, 0x65, 0x6f, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x52, 0x0f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x47, 0x65, 0x6f, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x79, 0x70,
	0x65, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x74, 0x79, 0x70, 0x65, 0x73, 0x12,
	0x19, 0x0a, 0x08, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x49, 0x64, 0x22, 0x8e, 0x01, 0x0a, 0x0c, 0x4c,
	0x61, 0x74, 0x4c, 0x6e, 0x67, 0x42, 0x6f, 0x75, 0x6e, 0x64, 0x73, 0x12, 0x3e, 0x0a, 0x09, 0x6e,
	0x6f, 0x72, 0x74, 0x68, 0x65, 0x61, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20,
	0x2e, 0x63, 0x6f, 0x6f, 0x70, 0x2e, 0x64, 0x72, 0x69, 0x76, 0x65, 0x72, 0x73, 0x2e, 0x67, 0x65,
	0x6f, 0x2e, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x2e, 0x4c, 0x61, 0x74, 0x4c, 0x6e, 0x67,
	0x52, 0x09, 0x6e, 0x6f, 0x72, 0x74, 0x68, 0x65, 0x61, 0x73, 0x74, 0x12, 0x3e, 0x0a, 0x09, 0x73,
	0x6f, 0x75, 0x74, 0x68, 0x77, 0x65, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20,
	0x2e, 0x63, 0x6f, 0x6f, 0x70, 0x2e, 0x64, 0x72, 0x69, 0x76, 0x65, 0x72, 0x73, 0x2e, 0x67, 0x65,
	0x6f, 0x2e, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x2e, 0x4c, 0x61, 0x74, 0x4c, 0x6e, 0x67,
	0x52, 0x09, 0x73, 0x6f, 0x75, 0x74, 0x68, 0x77, 0x65, 0x73, 0x74, 0x22, 0xb6, 0x02, 0x0a, 0x0f,
	0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x47, 0x65, 0x6f, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x12,
	0x3c, 0x0a, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x20, 0x2e, 0x63, 0x6f, 0x6f, 0x70, 0x2e, 0x64, 0x72, 0x69, 0x76, 0x65, 0x72, 0x73,
	0x2e, 0x67, 0x65, 0x6f, 0x2e, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x2e, 0x4c, 0x61, 0x74,
	0x4c, 0x6e, 0x67, 0x52, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x4b, 0x0a,
	0x0d, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x26, 0x2e, 0x63, 0x6f, 0x6f, 0x70, 0x2e, 0x64, 0x72, 0x69, 0x76,
	0x65, 0x72, 0x73, 0x2e, 0x67, 0x65, 0x6f, 0x2e, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x2e,
	0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0c, 0x6c, 0x6f,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x3e, 0x0a, 0x06, 0x62, 0x6f,
	0x75, 0x6e, 0x64, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x63, 0x6f, 0x6f,
	0x70, 0x2e, 0x64, 0x72, 0x69, 0x76, 0x65, 0x72, 0x73, 0x2e, 0x67, 0x65, 0x6f, 0x2e, 0x76, 0x31,
	0x62, 0x65, 0x74, 0x61, 0x31, 0x2e, 0x4c, 0x61, 0x74, 0x4c, 0x6e, 0x67, 0x42, 0x6f, 0x75, 0x6e,
	0x64, 0x73, 0x52, 0x06, 0x62, 0x6f, 0x75, 0x6e, 0x64, 0x73, 0x12, 0x42, 0x0a, 0x08, 0x76, 0x69,
	0x65, 0x77, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x63,
	0x6f, 0x6f, 0x70, 0x2e, 0x64, 0x72, 0x69, 0x76, 0x65, 0x72, 0x73, 0x2e, 0x67, 0x65, 0x6f, 0x2e,
	0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x2e, 0x4c, 0x61, 0x74, 0x4c, 0x6e, 0x67, 0x42, 0x6f,
	0x75, 0x6e, 0x64, 0x73, 0x52, 0x08, 0x76, 0x69, 0x65, 0x77, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x14,
	0x0a, 0x05, 0x74, 0x79, 0x70, 0x65, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x74,
	0x79, 0x70, 0x65, 0x73, 0x22, 0x64, 0x0a, 0x10, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x43,
	0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x6c, 0x6f, 0x6e, 0x67,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x6f, 0x6e,
	0x67, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x68, 0x6f, 0x72, 0x74,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x79, 0x70, 0x65, 0x73, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x05, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2a, 0xad, 0x01, 0x0a, 0x0c, 0x4c,
	0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x19, 0x0a, 0x15, 0x4c,
	0x4f, 0x43, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x49, 0x4e, 0x56,
	0x41, 0x4c, 0x49, 0x44, 0x10, 0x00, 0x12, 0x19, 0x0a, 0x15, 0x4c, 0x4f, 0x43, 0x41, 0x54, 0x49,
	0x4f, 0x4e, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x52, 0x4f, 0x4f, 0x46, 0x54, 0x4f, 0x50, 0x10,
	0x01, 0x12, 0x24, 0x0a, 0x20, 0x4c, 0x4f, 0x43, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x54, 0x59,
	0x50, 0x45, 0x5f, 0x52, 0x41, 0x4e, 0x47, 0x45, 0x5f, 0x49, 0x4e, 0x54, 0x45, 0x52, 0x50, 0x4f,
	0x4c, 0x41, 0x54, 0x45, 0x44, 0x10, 0x02, 0x12, 0x22, 0x0a, 0x1e, 0x4c, 0x4f, 0x43, 0x41, 0x54,
	0x49, 0x4f, 0x4e, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x47, 0x45, 0x4f, 0x4d, 0x45, 0x54, 0x52,
	0x49, 0x43, 0x5f, 0x43, 0x45, 0x4e, 0x54, 0x45, 0x52, 0x10, 0x03, 0x12, 0x1d, 0x0a, 0x19, 0x4c,
	0x4f, 0x43, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x41, 0x50, 0x50,
	0x52, 0x4f, 0x58, 0x49, 0x4d, 0x41, 0x54, 0x45, 0x10, 0x04, 0x42, 0x4b, 0x5a, 0x49, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6b, 0x65, 0x76, 0x69, 0x6e, 0x6d, 0x69,
	0x63, 0x68, 0x61, 0x65, 0x6c, 0x63, 0x68, 0x65, 0x6e, 0x2f, 0x61, 0x70, 0x69, 0x2d, 0x67, 0x65,
	0x6f, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x69, 0x64, 0x6c, 0x2f, 0x63,
	0x6f, 0x6f, 0x70, 0x2f, 0x64, 0x72, 0x69, 0x76, 0x65, 0x72, 0x73, 0x2f, 0x67, 0x65, 0x6f, 0x2f,
	0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_coop_drivers_geo_v1beta1_geocode_proto_rawDescOnce sync.Once
	file_coop_drivers_geo_v1beta1_geocode_proto_rawDescData = file_coop_drivers_geo_v1beta1_geocode_proto_rawDesc
)

func file_coop_drivers_geo_v1beta1_geocode_proto_rawDescGZIP() []byte {
	file_coop_drivers_geo_v1beta1_geocode_proto_rawDescOnce.Do(func() {
		file_coop_drivers_geo_v1beta1_geocode_proto_rawDescData = protoimpl.X.CompressGZIP(file_coop_drivers_geo_v1beta1_geocode_proto_rawDescData)
	})
	return file_coop_drivers_geo_v1beta1_geocode_proto_rawDescData
}

var file_coop_drivers_geo_v1beta1_geocode_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_coop_drivers_geo_v1beta1_geocode_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_coop_drivers_geo_v1beta1_geocode_proto_goTypes = []interface{}{
	(LocationType)(0),              // 0: coop.drivers.geo.v1beta1.LocationType
	(*GeocodeRequest)(nil),         // 1: coop.drivers.geo.v1beta1.GeocodeRequest
	(*GeocodeResponse)(nil),        // 2: coop.drivers.geo.v1beta1.GeocodeResponse
	(*ReverseGeocodeRequest)(nil),  // 3: coop.drivers.geo.v1beta1.ReverseGeocodeRequest
	(*ReverseGeocodeResponse)(nil), // 4: coop.drivers.geo.v1beta1.ReverseGeocodeResponse
	(*GeocodingResult)(nil),        // 5: coop.drivers.geo.v1beta1.GeocodingResult
	(*LatLngBounds)(nil),           // 6: coop.drivers.geo.v1beta1.LatLngBounds
	(*AddressGeometry)(nil),        // 7: coop.drivers.geo.v1beta1.AddressGeometry
	(*AddressComponent)(nil),       // 8: coop.drivers.geo.v1beta1.AddressComponent
	(*LatLng)(nil),                 // 9: coop.drivers.geo.v1beta1.LatLng
}
var file_coop_drivers_geo_v1beta1_geocode_proto_depIdxs = []int32{
	9,  // 0: coop.drivers.geo.v1beta1.GeocodeResponse.lat_lng:type_name -> coop.drivers.geo.v1beta1.LatLng
	9,  // 1: coop.drivers.geo.v1beta1.ReverseGeocodeRequest.lat_lng:type_name -> coop.drivers.geo.v1beta1.LatLng
	5,  // 2: coop.drivers.geo.v1beta1.ReverseGeocodeResponse.results:type_name -> coop.drivers.geo.v1beta1.GeocodingResult
	8,  // 3: coop.drivers.geo.v1beta1.GeocodingResult.address_components:type_name -> coop.drivers.geo.v1beta1.AddressComponent
	7,  // 4: coop.drivers.geo.v1beta1.GeocodingResult.address_geometry:type_name -> coop.drivers.geo.v1beta1.AddressGeometry
	9,  // 5: coop.drivers.geo.v1beta1.LatLngBounds.northeast:type_name -> coop.drivers.geo.v1beta1.LatLng
	9,  // 6: coop.drivers.geo.v1beta1.LatLngBounds.southwest:type_name -> coop.drivers.geo.v1beta1.LatLng
	9,  // 7: coop.drivers.geo.v1beta1.AddressGeometry.location:type_name -> coop.drivers.geo.v1beta1.LatLng
	0,  // 8: coop.drivers.geo.v1beta1.AddressGeometry.location_type:type_name -> coop.drivers.geo.v1beta1.LocationType
	6,  // 9: coop.drivers.geo.v1beta1.AddressGeometry.bounds:type_name -> coop.drivers.geo.v1beta1.LatLngBounds
	6,  // 10: coop.drivers.geo.v1beta1.AddressGeometry.viewport:type_name -> coop.drivers.geo.v1beta1.LatLngBounds
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_coop_drivers_geo_v1beta1_geocode_proto_init() }
func file_coop_drivers_geo_v1beta1_geocode_proto_init() {
	if File_coop_drivers_geo_v1beta1_geocode_proto != nil {
		return
	}
	file_coop_drivers_geo_v1beta1_latlng_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_coop_drivers_geo_v1beta1_geocode_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GeocodeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_coop_drivers_geo_v1beta1_geocode_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GeocodeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_coop_drivers_geo_v1beta1_geocode_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReverseGeocodeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_coop_drivers_geo_v1beta1_geocode_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReverseGeocodeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_coop_drivers_geo_v1beta1_geocode_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GeocodingResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_coop_drivers_geo_v1beta1_geocode_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LatLngBounds); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_coop_drivers_geo_v1beta1_geocode_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddressGeometry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_coop_drivers_geo_v1beta1_geocode_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddressComponent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_coop_drivers_geo_v1beta1_geocode_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_coop_drivers_geo_v1beta1_geocode_proto_goTypes,
		DependencyIndexes: file_coop_drivers_geo_v1beta1_geocode_proto_depIdxs,
		EnumInfos:         file_coop_drivers_geo_v1beta1_geocode_proto_enumTypes,
		MessageInfos:      file_coop_drivers_geo_v1beta1_geocode_proto_msgTypes,
	}.Build()
	File_coop_drivers_geo_v1beta1_geocode_proto = out.File
	file_coop_drivers_geo_v1beta1_geocode_proto_rawDesc = nil
	file_coop_drivers_geo_v1beta1_geocode_proto_goTypes = nil
	file_coop_drivers_geo_v1beta1_geocode_proto_depIdxs = nil
}
